<div class="col-md-8">
  <div id="product-gallery-slideshow" class="product-gallery-slideshow">
    <div class="product-gallery-detail">
      <div>
        <img
          class="product-gallery-image"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="product-gallery-image"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="product-gallery-image"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="product-gallery-image"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="product-gallery-image"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="product-gallery-image"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="product-gallery-image"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
    </div>
    <div class="product-gallery-nav">
      <div>
        <img
          class="img-responsive"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="img-responsive"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="img-responsive"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="img-responsive"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="img-responsive"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="img-responsive"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
      <div>
        <img
          class="img-responsive"
          data-lazy="https://secure.images.demo.dev.pixelmotiondemo.com/sliderimages/rolls-roycemotorcarsoc/5b4e77e1d9108c784d44e8eb.jpg"
          alt=""
        />
      </div>
    </div>
  </div>
</div>
